spring:
  application:
    name: locadora
  datasource:
    url: jdbc:mysql://localhost:3306/locadora
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update #validate / update / create / create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    smtp:
      auth: true
      starttls:
        enable: true
      host: smtp.mailtrap.io
      port: 2525
      username: your-mailtrap-username
      password: your-mailtrap-password



