spring:
  application:
    name: locadora
  datasource:
    url: jdbc:mysql://localhost:3306/locadora
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create #validate / update / create / create-drop
    properties:
      hibernate:
        format_sql: true
